### ISSUE TITLE
Need to fix

### ISSUE THREAD

**Issue by Tako-San** [derzhavin3016/ParaCL#20]
# Мелкие недочеты

- [x] 2. Заменить инт на наш тип. Размер типа должен быть машинно независимым.
- [x] 3. Заменить enum States, в котором только ﻿END, на constexpr, чтобы постоянно не приводить.
- [x] 4. StkFrame: prt -> ref.
- [x] 5. Документацию из .cc в .hh
- [x] 6. Возвращать из interpret код завершения.

Вынесем в отдельные issue
* 1. Сделать деструктор дерева в цикле. Рекурсивное удаление это больно.
* 7. Добавить автоматическое тестирование

**Comment by Tako-San** [comment]
Если что-то забыл, то пишите в комменты

**Comment by Tako-San** [comment]
Пункт 3 сделан

**Comment by derzhavin3016** [comment]
7. Добавить автоматическое тестирование

**Comment by Tako-San** [comment]
Пункт 5 сделан
