### ISSUE TITLE
Уровень 1. ParaCL compiler

### ISSUE THREAD

**Issue by Tako-San** [derzhavin3016/ParaCL#23]
Разработайте кодогенератор языка ParaCL в LLVM IR в объёме арифметика + if + while

Скомпилированная программа должна считывать со стандартного ввода всё,
что считывается, и печатать на стандартный вывод всё что нужно распечатать

Скрафтить хорошие тесты – важная часть задачи

**Comment by Tako-San** [comment]
* Mike Shah -- [Introduction to LLVM](https://www.youtube.com/watch?v=8pdQFUOlHLQ&ab_channel=MikeShah), его [сайт](http://www.mshah.io/).
* Chris Lattner -- [LLVM: A Compilation Framework for Lifelong Program Analysis & Transformation](https://llvm.org/pubs/2004-01-30-CGO-LLVM.pdf)
* Bridgers, Piovezan -- [LLVM IR Tutorial](https://www.youtube.com/watch?v=m8G_S5LwlTo&ab_channel=LLVM)

**Comment by Tako-San** [comment]
* [Kaleidoscope](https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/index.html)

**Comment by Tako-San** [comment]
* Naive [compiler](https://github.com/tilir/cpp-graduate/tree/master/13-llvm/01-naive) from tilir

**Comment by uslsteen** [comment]
* [LLVM documentation](https://llvm.org/doxygen/index.html)

**Comment by Tako-San** [comment]
Получили 2й уровень

**Comment by Tako-San** [comment]
Получили 2й уровень
